<?php
namespace Pluf\Data;

use Pluf\Exception as CoreException;

/**
 * All exceptions generated by Pluf DAta will use this class.
 */
class Exception extends CoreException
{

    public function __construct($options)
    {
        parent::__construct($options);
    }
}
